kind: Secret
apiVersion: v1
metadata:
  name: owlcms-config
  labels:
    app: owlcms
stringData:
  OWLCMS_DEVMODE: "true"
  OWLCMS_IP: ""
  OWLCMS_PIN: ""
  OWLCMS_RESETMODE: "true"
  OWLCMS_SMALLMODE: "false"
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app: postgres
stringData:
  POSTGRES_DB: "owlcms_db"
  POSTGRES_USER: "owlcms"
  POSTGRES_PASSWORD: "owlcms"
  POSTGRES_HOST: "postgres"
type: Opaque
